// Regenerates the contract ABIs the app uses from `contracts/out` (run `forge build` first):
//   node scripts/gen-abi.mjs
// Writes src/lib/curb/abi.ts (CurbAccount, CurbFactory) and src/lib/perpl/reader.ts (PerplBookReader's ABI and
// creation bytecode, run as a deployless eth_call, never deployed).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const web = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(web, "..", "contracts", "out");
const artifact = (file, name) => JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
const ts = (value) => JSON.stringify(value, null, 2);

const account = artifact("CurbAccount.sol", "CurbAccount");
const factory = artifact("CurbFactory.sol", "CurbFactory");
writeFileSync(
  join(web, "src/lib/curb/abi.ts"),
  `// Generated by scripts/gen-abi.mjs from contracts/out (forge build). Regenerate after changing CurbAccount or
// CurbFactory. The deployed factory's source is verified on Sourcify/MonadVision (exact match), see docs/CONTEXT.md.

export const curbAccountAbi = ${ts(account.abi)} as const;

export const curbFactoryAbi = ${ts(factory.abi)} as const;
`,
);

const reader = artifact("PerplBookReader.sol", "PerplBookReader");
writeFileSync(
  join(web, "src/lib/perpl/reader.ts"),
  `// Generated by scripts/gen-abi.mjs from contracts/out (forge build). PerplBookReader is never deployed: the app
// runs its creation code as a deployless eth_call (viem \`call({ code })\`) to read Perpl's book in one request.

export const perplBookReaderAbi = ${ts(reader.abi)} as const;

export const perplBookReaderBytecode = "${reader.bytecode.object}" as const;
`,
);
console.log("wrote src/lib/curb/abi.ts and src/lib/perpl/reader.ts");
